version: '3'
services:
  app:
    build: .
    container_name: node-auth
    environment:
      - DATABASE_URL=${DATABASE_URLDC}
      - NODE_ENV=development
      - PORT=8001
    ports:
      - '8001:8001'
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      # - /app/dist
  db:
    image: postgres:latest
    container_name: userDB
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
